# Generated by Django 5.1.15 on 2026-02-21 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_code', models.CharField(blank=True, max_length=10)),
                ('department', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Prefer not to say')], max_length=1, verbose_name='Gender')),
                ('primary_role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent / Guardian'), ('hr', 'HR Staff'), ('bursar', 'Bursar / Accountant'), ('head', 'Headteacher / Principal')], default='student', help_text='Main role for display, quick filters, and basic access rules', max_length=20, verbose_name='Primary Role')),
                ('department', models.CharField(blank=True, choices=[('sciences', 'Sciences'), ('languages', 'Languages'), ('humanities', 'Humanities')], help_text='Main teaching department (mostly for teachers)', max_length=30, null=True, verbose_name='Department')),
                ('form_level', models.CharField(blank=True, choices=[('form_1', 'Form 1'), ('form_2', 'Form 2'), ('form_3', 'Form 3'), ('form_4', 'Form 4')], help_text='Only relevant for students', max_length=10, null=True, verbose_name='Form Level')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('form_level', models.CharField(blank=True, choices=[('form_1', 'Form 1'), ('form_2', 'Form 2'), ('form_3', 'Form 3'), ('form_4', 'Form 4')], max_length=10)),
                ('stream', models.CharField(blank=True, max_length=2)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('user', models.OneToOneField(limit_choices_to={'primary_role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student profile',
                'verbose_name_plural': 'student profiles',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('department', models.CharField(blank=True, choices=[('sciences', 'Sciences'), ('languages', 'Languages'), ('humanities', 'Humanities'), ('technical', 'Technical / Vocational')], max_length=30)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('subjects_taught', models.ManyToManyField(blank=True, related_name='teachers', to='myapp.subject')),
                ('user', models.OneToOneField(limit_choices_to={'primary_role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'teacher profile',
                'verbose_name_plural': 'teacher profiles',
            },
        ),
    ]
