# Generated by Django 5.1.15 on 2026-02-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_admission',
            field=models.DateField(null=True),
        ),
    ]
