# Generated by Django 5.1.15 on 2026-02-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_studentprofile_date_of_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='date_of_admission',
        ),
    ]
