# Generated by Django 5.1.15 on 2026-02-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_studentprofile_date_of_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='admission_number',
        ),
    ]
